site_name: BHoM documentation
copyright: Copyright &copy; 2018 - 2022 BHoM
site_url: https://bhom.xyz/documentation/
repo_url: https://github.com/BHoM/documentation
edit_uri: edit/main/docs/

theme:
  name: material
  logo: _logos/logo.png
  favicon: _logos/favicon.ico
  palette:
    primary: white
    accent: pink
  icon:
    edit: material/pencil 
    view: material/eye

  features:
    - navigation.tracking
    - navigation.top
    - content.action.edit
    - content.action.view
    - content.tabs.link # allows to link to specific Content tab. See https://squidfunk.github.io/mkdocs-material/reference/content-tabs/#linked-content-tabs

plugins:
  - search
  - awesome-pages # allows to customise the ordering of pages.
  - git-revision-date-localized: # Displays date created/modified on the page. The below configurations are bugged, so only date modified works.
    # enable_creation_date: true
    # fallback_to_build_date: true
    


markdown_extensions:
  - attr_list # allows to add HTML/CSS attributes to almost every Markdown element, useful for e.g. aligning an image to the left/right (can't do centre though! use md_in_html instead)
  - md_in_html # allows to add markdown within HTML elements, useful for e.g. adding image captions or centering an image
  
  - pymdownx.betterem # Wider support to markdown symbols
  
  # Code syntax highlighting
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed: # enables Content tabs.
    alternate_style: true 
  - pymdownx.superfences # allows to add markdown to Content tabs. See https://squidfunk.github.io/mkdocs-material/reference/content-tabs/#embedded-content

  # Mathjax support
  - pymdownx.arithmatex:
      generic: true

  # Call-outs and note boxes ('admonition')
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra_javascript: 
  # Also required for Mathjax support
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/BHoM
      name: BHoM on Github